rtitle: Seguridad Informática
description: "Web en el que voy a subir tanto como write-ups de CTF, tanto como artículos sobre explotación de vulnerabilidades en un entornos controlados."
author:
  name: "meretec"
  email: "meretec@proton.me"
  url: "https://cerodah.github.io/blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "cerodah"
year : "XXXX"
